from vlde.error import ValidateError, RulesError
from vlde.validate import Validator

__name__ == 'vlde'
